source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/plug.kak" noload
plug "alexherbo2/prelude.kak"
plug "alexherbo2/terminal-mode.kak"
plug "alexherbo2/connect.kak" config %{
    require-module connect
}

plug "andreyorst/fzf.kak" config %{
    require-module fzf
    require-module fzf-file
    require-module fzf-buffer
    set-option global fzf_file_command fd
}

plug "ul/kak-lsp" config %{
    # set global lsp_cmd "kak-lsp -s %val{session} -vvv --log /home/kayhide/tmp/kak-lsp.log"
}

add-highlighter global/ show-matching
add-highlighter global/ wrap

hook global WinCreate ^[^*]+$ %{
    add-highlighter window/ number-lines -hlcursor
}

map global user f ': fzf-mode<ret>' -docstring 'fzf'
map global user l ': enter-user-mode<space>lsp<ret>' -docstring 'lsp'
map global user F ': format<ret>' -docstring 'format'

declare-user-mode space
map global normal <space> ': enter-user-mode<space>space<ret>'
map global space <space> <space> -docstring 'remove all sels except main'
map global space <semicolon> ': comment-line<ret>' -docstring '(un)comment selected lines'

declare-user-mode space-buffer
map global space b ': enter-user-mode<space>space-buffer<ret>' -docstring 'buffer'
map global space-buffer b ': fzf-buffer<ret>' -docstring 'open buffer'
map global space-buffer d ': delete-buffer<ret>' -docstring 'delete current buffer'
map global space-buffer D ': fzf-delete-buffer<ret>' -docstring 'delete buffer'
map global space-buffer R ': edit!<ret>' -docstring 'reload buffer'

declare-user-mode space-file
map global space f ': enter-user-mode<space>space-file<ret>' -docstring 'file'
map global space-file f ': fzf-file<ret>' -docstring 'find file'
map global space-file s ': write<ret>' -docstring 'save file'

declare-user-mode space-file-e
map global space-file e ': enter-user-mode<space>space-file-e<ret>' -docstring 'file-e'
map global space-file-e d ': edit-kakrc<ret>' -docstring 'edit kakrc'

declare-user-mode space-terminal
map global space <ret> ': enter-user-mode<space>space-terminal<ret>' -docstring 'terminal'
map global space-terminal t ': $<space>kitty --listen-on "unix:@%sh{date +%s}"<ret>' -docstring 'open kitty'
map global space-terminal a ': $<space>kitty --listen-on "unix:@%sh{date +%s}" :a<ret>' -docstring 'open new client'
map global space-terminal r ': $<space>kitty --listen-on "unix:@%sh{date +%s}" ranger --selectfile "%val{buffile}" <ret>' -docstring 'launch ranger'
map global space-terminal g ': $<space>kitty --listen-on "unix:@%sh{date +%s}" tig<ret>' -docstring 'launch tig'

declare-user-mode space-error
map global space e ': enter-user-mode<space>space-error<ret>' -docstring 'error'
map global space-error n '<esc>: lsp-find-error --include-warnings<ret>' -docstring 'find next error or warning'
map global space-error p '<esc>: lsp-find-error --include-warnings --previous<ret>' -docstring 'find previous error or warning'
map global space-error N '<esc>: lsp-find-error<ret>' -docstring 'find next error'
map global space-error P '<esc>: lsp-find-error --previous<ret>' -docstring 'find previous error'

declare-user-mode space-project
map global space p ': enter-user-mode<space>space-project<ret>' -docstring 'project'
map global space-project a '<esc>: alt<ret>' -docstring 'edit alternative file'

declare-user-mode space-toggle
map global space t ': enter-user-mode<space>space-toggle<ret>' -docstring 'toggle'
map global space-toggle w '<esc>: toggle-highlighter window/ show-whitespaces<ret>' -docstring 'toggle whitespaces'

declare-user-mode space-text
map global space x ': enter-user-mode<space>space-text<ret>' -docstring 'text'

declare-user-mode space-text-lines
map global space-text l ': enter-user-mode<space>space-text-lines<ret>' -docstring 'lines'
map global space-text-lines s '| sort<ret>' -docstring 'sort'
map global space-text-lines S '| sort --reverse<ret>' -docstring 'sort reverse'
map global space-text-lines u '| uniq<ret>' -docstring 'uniq'

def toggle-highlighter -params 2.. %{
    try %{
        add-highlighter %arg{@}
    } catch %{
        evaluate-commands %sh{
            if [[ $1 == */ ]]; then
                path="$1$(shift; printf '%s' "$*" | sed 's_/_<slash>_g' | sed 's/ /_/g')"
            else
                path="$1"
            fi
            printf "remove-highlighter '%s'" "$path"
        }
    }
}

def edit-kakrc -docstring 'edit kakrc' %{
    edit! "%val{config}/kakrc"
}

# Seach case insensitive
map global normal / /(?i)
map global normal <a-/> <a-/>(?i)

# Local configs

source "%val{config}/clipboard.kak"
source "%val{config}/psc-ide.kak"
source "%val{config}/erlang.kak"
# source "%val{config}/reload-kakrc.kak"

# Nix
hook global WinSetOption filetype=nix %{
    set-option window tabstop 2
    set-option window indentwidth 2
}

# Yaml
hook global WinSetOption filetype=yaml %{
    set-option window tabstop 2
    set-option window indentwidth 2
}

# JavaScript / Json
hook global WinSetOption filetype=javascript|json %{
    set-option window tabstop 2
    set-option window indentwidth 2
    set-option window formatcmd "prettier --stdin-filepath=%val{buffile}"
}

# Css
hook global WinSetOption filetype=css %{
    set-option window tabstop 2
    set-option window indentwidth 2
    set-option window formatcmd "prettier --stdin-filepath=%val{buffile}"
}

# Html
hook global WinSetOption filetype=html %{
    set-option window tabstop 2
    set-option window indentwidth 2
    set-option window formatcmd "prettier --stdin-filepath=%val{buffile}"
}

# Svelte
hook global WinSetOption filetype=svelte %{
    set-option window tabstop 2
    set-option window indentwidth 2
}

# Erlang
hook global WinSetOption filetype=erlang %{
    set-option window tabstop 2
    set-option window indentwidth 2
    set-option buffer comment_line '%'
}

# Elixir
hook global WinSetOption filetype=elixir %{
    set-option window tabstop 2
    set-option window indentwidth 2
    set-option buffer comment_line '#'
}

hook global WinSetOption filetype=eex %{
    set-option window tabstop 2
    set-option window indentwidth 2
}

# Ruby
hook global WinSetOption filetype=ruby %{
    set-option window tabstop 2
    set-option window indentwidth 2
}

# Rust
hook global WinSetOption filetype=rust %{
    set-option window tabstop 4
    set-option window indentwidth 4
    set-option window formatcmd "rustfmt"
    lsp-enable-window
}

# Haskell
define-command haskell-alternative-file -docstring 'Jump to the alternate file (implementation ↔ test)' %{ evaluate-commands %sh{
    case $kak_buffile in
        */Test/*.hs)
            basepath=$(echo $kak_buffile | sed s+.*Test/++)
            altfile=$(find src -path "*/$basepath" | head -n 1)
            [ ! -f $altfile ] && echo "fail 'implementation file not found'" && exit
        ;;
        *.hs)
            basepath=$(echo $kak_buffile | sed s+.*src/++)
            altfile=$(find test -path "*/$basepath" | head -n 1)
            [ ! -f $altfile ] && echo "fail 'test file not found'" && exit
        ;;
        *)
            echo "fail 'alternative file not found'" && exit
        ;;
    esac
    echo "edit $altfile"
}}

hook global WinSetOption filetype=haskell %{
    set-option window tabstop 2
    set-option window indentwidth 2
    set-option window formatcmd "stylish-haskell"
    alias window alt haskell-alternative-file
}

# PureScript
declare-user-mode user-purescript
declare-user-mode user-purescript-import
hook global WinSetOption filetype=purescript %{
    set-option window tabstop 2
    set-option window indentwidth 2
    set-option window formatcmd "purty %val{buffile}"
    lsp-enable-window

    set-option buffer comment_line '--'
    set-option buffer comment_block_begin '{-'
    set-option buffer comment_block_end '-}'

    map window user m ': enter-user-mode<space>user-purescript<ret>'
    map window user-purescript i ': enter-user-mode<space>user-purescript-import<ret>'
    map window user-purescript-import a ': psc-ide-add-import<ret>'
}

# Python
define-command python-alternative-file -docstring 'Jump to the alternate file (implementation ↔ test)' %{ evaluate-commands %sh{
    case $kak_buffile in
        *test_*.py)
            altfile=$(eval echo $(echo $kak_buffile | sed s+test/+src/+';'s/test_//))
            if [ ! -f $altfile ]; then
                altfile=$(eval echo $(echo $kak_buffile | sed s+test/+src/+';'s/test_//';'s+.py+/__init__.py+))
                [ ! -f $altfile ] && echo "fail 'implementation file not found'" && exit
            fi
        ;;
        *__init__.py)
            path=$kak_buffile
            basename="test_$(basename $(dirname $path)).py"
            altdir=$(dirname $(dirname $(echo $path | sed s+src/+test/+)))
            altfile="$altdir/$basename"
            [ ! -f $altfile ] && echo "fail 'test file not found $altfile'" && exit
        ;;
        *.py)
            path=$kak_buffile
            basename=test_$(basename $path)
            altdir=$(dirname $(echo $path | sed s+src/+test/+))
            altfile="$altdir/$basename"
            [ ! -f $altfile ] && echo "fail 'test file not found $altfile'" && exit
        ;;
        *)
            echo "fail 'alternative file not found'" && exit
        ;;
    esac
    echo "edit $altfile"
}}

hook global WinSetOption filetype=python %{
    alias window alt python-alternative-file
}

